### ISSUE TITLE
Not cryptographically random

### ISSUE THREAD

**Issue by markstos** [Alex1990/randstr#2]
`Math.random()` is [not cryptographically random](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random). It seems worth mentioning this in the README, or switching to a random number generator which is considered cryptographically random, such as `crypto.randomBytes` in Node.js

**Comment by Alex1990** [comment]
Thanks! At present, this module is used to generate simply random strings and is not suitable for cryptography. I updated the README.
